### ISSUE TITLE
Memory Import with merge bricks Device

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#231] opened 2016-08-24 18:55 UTC
### Expected behavior
If you have 2 MP and modify Password A on MP1 and Password B on MP2 and then merge the binary of MP1 with MP2 it should still work.

### Actual behavior
When importing the MP1 data it merges it. Opening Credential Management Mode sais it finds an empty node, and the device seems bricked (in case i cannot open the credential mode again). MP2 has adopted the changes from MP1, but the changed Password B on MP2 is lost (or reset to the value from MP1).

### Step by step guide to reproduce the problem
Change a password on each device, but make sure its not the same password.
Export the data of MP1 and import it to MP2.
Open credential management mode on MP2 and it gives the empty node error.
You can also restart the app and replug the device and the error will still be there.
All I've done afterwards was to type the Password A and B from MP2 (which typed all information the MP1 had before).
Then I tried an integrity check.

**Integrity check sais the device is okay. If you then enter the credential management mode again it gives no error.**

I've then tried to change Password B again and import MP1 database and then it worked fine.

I've only tries this once, because Its my productive MP setup. I have serious problems if my MP device fails, so I am not going to risk another brick again.

### Mooltipass version
MP1 is the original MP with the initital firmware. MP2 is the Mini Beta unit.

**Comment by limpkin** [comment] 2016-08-24 20:01
Hello there,

Followed your exact instructions and couldn't reproduce it... I'm affraid I'll have to close this issue then.
Please re-open if you can reproduce it.

**Comment by NicoHood** [comment] 2016-08-28 10:02
I could not reproduce this anymore. Tried it 2 times now. I am also not sure if it was a proble  on the PC or firmware side. Hope it won't happen again.

**Comment by NicoHood** [comment] 2016-09-01 19:50
I've got another issue related to the memory merge mode:
I've got a "pgp" entry on both devices. Now I've created a new entry also with the name/category "pgp" on my normal MP and then exported the file. I've imported it on the Mini, but its not in the database. I've double checked and made sure its on the normal MP and I've tried ex/import again. No chance to get this password to the other device.

Do you want me to open a new issue or summarize this here? I suggest to reopen this issue, as it still exists for me. I cannot reopen, once you've closed it.

**Comment by NicoHood** [comment] 2016-09-03 11:01
@limpkin Can you please reopen? This is a serious issue, as My PGP password cannot be transfered.

Now I am not sure if the memory export misses this entry at all or if just the merge on the MP Mini fails. I've added other entries on the old MP that do get merged. Only the 2nd PGP entry is missing.

Here is the output of the memory export. I've changed some of the data, so it shouldn't be readable. Maybe you can check if this entry can contain2 data sets of if that even missed the entry. Its the only pgp entry in the memory export.
```
address":[56,8],"name":"pgp","data":{"0":0,"1":0,"2":22,"2":9,"4":1,"5":9,"5":88,"4":10,"8":112,"9":102,"10":112,"11":0,"12":0,"12":0,"14":0,"15":0,"15":0,"14":0,"18":0,"19":0,"20":0,"21":0,"22":0,"22":0,"24":0,"25":0,"25":0,"24":0,"28":0,"29":0,"20":0,"21":0,"22":0,"22":0,"24":0,"25":0,"25":0,"24":0,"28":0,"29":0,"40":0,"41":0,"42":0,"42":0,"44":0,"45":0,"45":0,"44":0,"48":0,"49":0,"50":0,"51":0,"52":0,"52":0,"54":0,"55":0,"55":0,"54":0,"58":0,"59":0,"50":0,"51":0,"52":0,"52":0,"54":0,"55":0,"55":0,"54":0,"58":0,"59":0,"40":0,"41":0,"42":0,"42":0,"44":0,"45":0,"45":0,"44":0,"48":0,"49":0,"80":0,"81":0,"82":0,"82":0,"84":0,"85":0,"85":0,"84":0,"88":0,"89":0,"90":0,"91":0,"92":0,"92":0,"94":0,"95":0,"95":0,"94":0,"98":0,"99":0,"100":0,"101":0,"102":0,"102":0,"104":0,"105":0,"105":0,"104":0,"108":0,"109":0,"110":0,"111":0,"112":0,"112":0,"114":0,"115":0,"115":0,"114":0,"118":0,"119":0,"120":0,"121":0,"122":0,"122":0,"124":0,"125":0,"125":0,"124":0,"128":0,"129":0,"120":0,"121":0}},
```

**Comment by limpkin** [comment] 2016-09-04 19:36
Ok here's what I've done:

- create a new user on mooltipass standard
- added pgp service with "usera" inside
- exported db from the mp standard
- imported the db on the mp mini
- entered mmm, checked the credential
- added "userb" inside the pgp service on mooltipass standard
- exported db
- imported db on mp mini
- went to mmm, checked that "userb" was there

Until you actually provide us with a reproducible bug, I'm affraid I won't open this "issue" again.

**Comment by NicoHood** [comment] 2016-09-04 19:52
Okay, how does the memory export data look like? Does it have 2 entries? We need to know if the error happens on export or import. I've posted my single pgp entry above. This would help for the next step.

**Comment by limpkin** [comment] 2016-09-04 19:56
export data has two entries, everything is as expected.

**Comment by NicoHood** [comment] 2016-09-04 20:20
Then there must be something wrong with the old MP then. I am using firmware 1.0. Not sure if you changed something dramatical till then.

However this is a pitty as I cannot export the data. Its weird, as its shown in the MMM, but not in the memory export. So possibly "just" something wrong with the app and the export function and not the MP firmware itself.

Any further steps I could do (expect providing a smaller testcase which I am trying)? Maybe I can run some custom code to request special entrys in my MP? However we need to be extremely careful as this is my productive one.

**Comment by limpkin** [comment] 2016-09-04 20:36
All we ask since you've started reporting issues **is a reproducible bug**

**Comment by NicoHood** [comment] 2016-09-11 09:19
Some more information when debugging this issue (will edit over the time if i find new infos):

When analyzing the MP memory export I can find 1 entry for `pgp`, ` 3 entries for `email1` (also used with other entries) and 1 entry for the new pgp entry `email2`. This means the memory export has this data. The question now is why the mini does not want to import the data.

I do not know the details of the memory structure, but it might be possible that the data at the specific address is already used? Or will it just chose a different addres?

The missing entry looks like this in the export:
```
{"address":[88,10],"name":"mail2","data":{
```

The address itself is not used in the mini. But also the `mail2` entry is missing. So the import fails to safe this data.

**Comment by limpkin** [comment] 2016-09-11 10:11
you may dig into our chrome app to enable the debug output (booleans at the beginning of each js file in the vendor folder) to exactly know what problems were found by the app.

**Comment by NicoHood** [comment] 2016-09-11 10:35
The integrity check sais:
```
# Note: to clarify: I've replaced the real email with mail1 and mail2 to avoid spam.
# I try to keep consistent with my bug reports above
# mail1: existing entry for pgp and mail2 is the new entry
Merging procedure started
memmgmt.js:162 CTR value OK
memmgmt.js:162 pgp : adding new child mail2 in the mooltipass...
memmgmt.js:162 Total number of addresses required: 1
memmgmt.js:162 Received 31 free addresses, current total: 31
memmgmt.js:162 
memmgmt.js:162 Generating merge packets
memmgmt.js:162 Node data different for child mail1
memmgmt.js:162 Adding new child mail2
memmgmt.js:162 Favorite 3 : couldn't find child node mail2 on pgp

[...]

memmgmt.js:162 Parent node pgp first child is mail1 at address 160,9
memmgmt.js:857 Problem with previous child address: 129,8 instead of 0,0

[...]

# Important note: mail1 entry of PGP is used as favorite!
# and mail1 also has a parent also named mail1, if that matters. also a favorite
# favorite is normall the mail2 pgp entry, which is empty here due to the bug
Checking for orphan child nodes...
memmgmt.js:913 Found orphan node:mail2 at address 129,8 , deleting it...
memmgmt.js:162 Favorite 0 is valid: REMOVED on REMOVED
memmgmt.js:162 Favorite 1 is valid: REMOVED on REMOVED
memmgmt.js:162 Favorite 2 is valid: REMOVED on REMOVED
memmgmt.js:162 Favorite 3 is empty
memmgmt.js:162 Favorite 4 is valid: mail1 on mail1
memmgmt.js:162 Favorite 5 is valid: REMOVED on REMOVED
memmgmt.js:162 Favorite 6 is valid: REMOVED on REMOVED
memmgmt.js:162 Favorite 7 is valid: mail1 on pgp

[...]

Deleting child node mail2
[...]
Child node mail1 differs... updating it
Problems with memory contents... sending correction packets
```

Does this mean the node `mail2` is not referenced by any other node and `mail1` points into nowhere? I might be wrong. I can do further debugging, any ideas where to look at now?

**Comment by limpkin** [comment] 2016-09-11 11:19
could you rename mail1 and mail2 in such a way they don't break alphabetical order?

**Comment by limpkin** [comment] 2016-09-11 12:55
from that debug, it seems the parent node first child addresss isn't properly updated, while mmail1 gets it's previous node address correctly updated. I wonder if it is connected to the fact that amail2 is tagged as favorite.
You may read the merging code here: https://github.com/limpkin/mooltipass/blob/master/chrome_app/vendor/mooltipass/memmgmt.js#L2029

**Comment by NicoHood** [comment] 2016-09-11 13:21
So to better understand:
PGP is the parent which links to the first child mmail1:
`pgp`<->`mmail1`

If you then add `amail2`, will it be placed between `pgp` and `mmail1` or after `mmail1`?
`pgp`<-> `amail2` <-> `mmail1`
`pgp`<->`mmail1` <-> `amail2`

**Comment by limpkin** [comment] 2016-09-11 13:23
amail2 should then become first child of pgp and prev child of mmail1

**Comment by NicoHood** [comment] 2016-09-11 13:53
So to me the bug looks like this:
`pgp` -> `mmail1`
`amail2` <- `mmail`` -> `null?`
`null` <- `amail2` -> `mmail?`

```
memmgmt.js:162 Adding new child amail2
memmgmt.js:162 Favorite 3 : couldn't find child node amail2 on pgp
```
-> This means `amail2` is not found in the chain starting with `pgp`

```
memmgmt.js:162 Parent node pgp first child is mmail1 at address 160,9
memmgmt.js:857 Problem with previous child address: 129,8 instead of 0,0
```
-> This means `pgp` points at `mmail1` but `mmail1` not back at `pgp`, but it does point at `amail2` which you can see later from the addresses.

```
Checking for orphan child nodes...
memmgmt.js:913 Found orphan node:amail2 at address 129,8 , deleting it...
```
After the previous child for `mmail1` got fixed by the app `amail2` points to `mmail1` which does not point back to `amail2`. And the previous child of `amail2` is null.

So this means, as you already stated, pgps first child node is not set properly. It should be updated to `amail2`.

**Comment by limpkin** [comment] 2016-09-11 13:57
>> memmgmt.js:162 Favorite 3 : couldn't find child node amail2 on pgp

this is normal, as your new mpm doesn't know amail2...

>> memmgmt.js:857 Problem with previous child address: 129,8 instead of 0,0

I think it means the prev child addr of mmail1 is incorrect

>> This means pgp points at mmail1 but mmail1 not back at pgp

mmail1 shouldn't point to pgp (child don't point to parents)

to me it seems that pgp first child addr isn't updated to poin to amail2... and i wonder if it is caused by the fact that amail2 is tagged as favorite.

**Comment by NicoHood** [comment] 2016-09-11 14:16
I currently try to debug this with my little knowledge of javascript. It could be possibly in this part of the code:
https://github.com/limpkin/mooltipass/blob/master/chrome_app/vendor/mooltipass/memmgmt.js#L2142

If I add some more debug log like this you can see that nothing changes here:
```javascript
mooltipass.memmgmt.consoleLog(mooltipass.memmgmt.importedCurServiceNodes[i].name + " : parternt i child address " + mooltipass.memmgmt.getFirstChildAddress(mooltipass.memmgmt.importedCurServiceNodes[i].data));
mooltipass.memmgmt.consoleLog(mooltipass.memmgmt.importedCurServiceNodes[j].name + " : parternt j child address " + mooltipass.memmgmt.getFirstChildAddress(mooltipass.memmgmt.importedCurServiceNodes[j].data));
new_children_for_existing_parents.push({'parrentAddress': mooltipass.memmgmt.clonedCurServiceNodes[j].address, 'name': mooltipass.memmgmt.importedCurLoginNodes[k].name, 'data': mooltipass.memmgmt.importedCurLoginNodes[k].data});
mooltipass.memmgmt.consoleLog(mooltipass.memmgmt.importedCurServiceNodes[i].name + " : parternt i child address " + mooltipass.memmgmt.getFirstChildAddress(mooltipass.memmgmt.importedCurServiceNodes[i].data));
mooltipass.memmgmt.consoleLog(mooltipass.memmgmt.importedCurServiceNodes[j].name + " : parternt j child address " + mooltipass.memmgmt.getFirstChildAddress(mooltipass.memmgmt.importedCurServiceNodes[j].data));
```

If i am not completely wrong, this value should change, but it does not:
```
pgp : parternt i child address 88,10
pgp : parternt j child address 88,10
pgp : parternt i child address 88,10
pgp : parternt j child address 88,10
```

But I might be wrong, or my code is.

**Comment by limpkin** [comment] 2016-09-11 14:22
if that was the case, then trying to import a db where a parent's first child changes would re-create your bug... would you be able to try that?

**Comment by NicoHood** [comment] 2016-09-11 14:28
Yes! I could reproduce the bug now. The new entry needs to be before the existing entry. I always used an entry name that is later in the alphabet.

To me it seems the bug is here, where the parent should be updated, but is not updated to the new node:
https://github.com/limpkin/mooltipass/blob/master/chrome_app/vendor/mooltipass/memmgmt.js#L2407

**Comment by limpkin** [comment] 2016-09-11 14:53
Could you try changing tempChildAddress in https://github.com/limpkin/mooltipass/blob/master/chrome_app/vendor/mooltipass/memmgmt.js#L2510 to tempFirstChildAddress ?

**Comment by limpkin** [comment] 2016-09-11 14:59
Hmmm actually maybe replace tempChildAddress at
- https://github.com/limpkin/mooltipass/blob/master/chrome_app/vendor/mooltipass/memmgmt.js#L2342
- https://github.com/limpkin/mooltipass/blob/master/chrome_app/vendor/mooltipass/memmgmt.js#L2409
 
to tempChildAddress

**Comment by NicoHood** [comment] 2016-09-11 15:03
That solved the issue! I replaced those 2 lines as suggested.

**Comment by limpkin** [comment] 2016-09-11 15:03
can you make a PR for these 2 lines? thanks

**Closed** 2016-09-11 17:54 UTC

**Comment by NicoHood** [comment] 2016-09-11 19:36
I hope that this fixes also the zero node issue I originally had and cannot reproduce anymore.
Thanks for the support :)
