### ISSUE TITLE
Chrome Extension Not Responding

### ISSUE THREAD

**Issue by sonofapharmacist** [limpkin/mooltipass#388] opened 2017-05-01 14:08 UTC
Use one of the two templates below and delete the rest. All issues not following a template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Chrome browser, leave tons of tabs open over a few hours, chrome continues to operate like a normal web browser and mooltipass extension continues to operate normally.
### Actual behavior
In Chrome (58.0.3029.81 (64-bit) windows 10 and windows 7), when leaving the Chrome browser open for extended periods of time with multiple tabs, i am unable to navigate the browser in any tab as the status bar in bottom left says "waiting for mooltipass extension..."  Mooltipass extension at this point does not respond either. I can open the chrome task manager, kill mooltipass extension and all goes well.  I can reload mooltipass extension at this point and it works fine.  I can't remember if this happened only after i started pinning http://e.ggtimer.com/30%20minutes to my browser and if it corresponds with its pop-up / alerting behavior.
### Step by step guide to reproduce the problem
In Chrome (58.0.3029.81 (64-bit) windows 10 and windows 7), when leaving the Chrome browser open for extended periods of time with multiple tabs, i am unable to navigate the browser in any tab as the status bar in bottom left says "waiting for mooltipass extension..."  Mooltipass extension at this point does not respond either. I can open the chrome task manager, kill mooltipass extension and all goes well.  I can reload mooltipass extension at this point and it works fine.  I can't remember if this happened only after i started pinning http://e.ggtimer.com/30%20minutes to my browser and if it corresponds with its pop-up / alerting behavior.
### Mooltipass version
mooltipass mini v1.2 #12345
Which Mooltipass do you use? What is its firmware version? You may see the firmware version by going to the settings tab of our official App.

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment] 2017-05-01 14:11
Hello there,
Thanks for the bug report, we'll investigate. In the mean time, if you have a more precise way to reproduce the problem this would be greatly appreciated.

**Comment by kbembedded** [comment] 2017-05-03 02:49
I can say that I have had this issue as well.  In both Win7 with chrome, as well as a chromebook.  Its far and few between and I cannot comment on a reliable way to reproduce it.

**Comment by limpkin** [comment] 2017-05-16 18:12
Hello everyone,

did you manage to find a reliable way to reproduce the problem?

**Comment by kbembedded** [comment] 2017-05-17 05:55
No, but if I see it again I will try and grab console information, now that I know how to do that.  It has happened once since the last time I said something here.

**Comment by aouadahi** [comment] 2017-05-20 16:33
I had a similar issue, but with my addblocker.
Too many tabs, and sometimes i can't load a new page, and i have the "waiting for xxx extension" on the bottom left.
I didn't try the chrome task manager to kill it.
The issue is very random, i changed my addblocker but i will have it sometime.
Im not sure it's mootipass specific.

**Comment by NoahAndrews** [comment] 2017-09-15 01:28
It's definitely Mooltipass specific. It's just a bug that other extensions are capable of having as well.

**Comment by aouadahi** [comment] 2017-09-15 02:27
I had the same issue with others extensions too.

**Comment by limpkin** [comment] 2017-12-12 14:25
Hello everyone,

Are you still experiencing this issue?

Mathieu

**Comment by sonofapharmacist** [comment] 2017-12-12 14:33
Not since moving to Moolticute

**Comment by sonofapharmacist** [comment] 2017-12-12 14:34
Err and Firefox

**Comment by limpkin** [comment] 2017-12-12 14:36
neat :)

**Comment by NoahAndrews** [comment] 2017-12-12 17:13
I've also moved to Firefox and Moolticute, so I can't say if it's still a problem or not either.

**Comment by limpkin** [comment] 2017-12-12 17:14
let's close it until someone brings it up again.

**Closed by limpkin** 2017-12-12 17:14 UTC
Labels: bug

**Comment by burner-** [comment] 2018-01-30 20:01
I can confirm that I have that same problem with my laptop and my desktop. I first think that this is because flapping usb channel but then I buy new computer with fresh install and problem continues. Common thing is that I have tons of tabs. I dont have other extensions but I have noticed that this problem comes mostly after waking up from sleep. I am not familiar with mootipass code but my guess is that if there is some kind device connection with states it have race condition when you have lot of chrome tabs/windows and device got reconnected. I think that problem needs to reopen because it looks to occur with chrome + win10 combination with all my machines & devices. It is quite random but still annoying.

**Comment by NoahAndrews** [comment] 2018-01-30 20:03
I also always have tons of tabs open, including back when I used Chrome and had this issue. 

---- On Tue, 30 Jan 2018 15:01:39 -0500 notifications@github.com wrote ----

I can confirm that I have that same problem with my laptop and my desktop. I first think that this is because flapping usb channel but then I buy new computer with fresh install and problem continues. Common thing is that I have tons of tabs. I dont have other extensions but I have noticed that this problem comes mostly after waking up from sleep. I am not familiar with mootipass code but my guess is that if there is some kind device connection with states it have race condition when you have lot of chrome tabs/windows and device got reconnected. I think that problem needs to reopen because it looks to occur with chrome + win10 combination with all my machines & devices. It is quite random but still annoying.
